const plaidTransactions = [
  // Julio
  {
    date: "2024-07-03",
    amount: -23.5,
    logo_url: "",
    merchant_name: "Burger King",
    name: "Burger King Meal",
    category: ["Food and Drink", "Restaurants"],
  },
  {
    date: "2024-07-07",
    amount: -55,
    logo_url: "",
    merchant_name: "Walmart",
    name: "Walmart Groceries",
    category: ["Food and Drink", "Groceries"],
  },
  {
    date: "2024-07-14",
    amount: -11,
    logo_url: "",
    merchant_name: "Starbucks",
    name: "Starbucks Coffee",
    category: ["Food and Drink", "Coffee Shop"],
  },
  {
    date: "2024-07-18",
    amount: -20,
    logo_url: "",
    merchant_name: "Panda Express",
    name: "Panda Express Meal",
    category: ["Food and Drink", "Restaurants"],
  },  
  {
    date: "2024-07-05",
    amount: -90,
    logo_url: "",
    merchant_name: "Coursera",
    name: "Coursera Subscription",
    category: ["Education", "Subscription"],
  },
  {
    date: "2024-07-10",
    amount: -110,
    logo_url: "",
    merchant_name: "Udacity",
    name: "Udacity Payment",
    category: ["Education", "Subscription"],
  },  
  {
    date: "2024-07-15",
    amount: -60,
    logo_url: "",
    merchant_name: "Skillshare",
    name: "Skillshare Membership",
    category: ["Education", "Subscription"],
  },
  {
    date: "2024-07-21",
    amount: -125,
    logo_url: "",
    merchant_name: "Online University",
    name: "Monthly Course Subscription",
    category: ["Education", "Subscription"],
  },
  {
    date: "2024-07-10",
    amount: -35,
    logo_url: "",
    merchant_name: "CVS Pharmacy",
    name: "Personal Care",
    category: ["Shopping", "Personal Care"],
  },
  {
    date: "2024-07-20",
    amount: -50,
    logo_url: "",
    merchant_name: "Home Depot",
    name: "Cleaning Supplies",
    category: ["Shopping", "Utilities"],
  },
  {
    date: "2024-07-25",
    amount: -40,
    logo_url: "",
    merchant_name: "Petco",
    name: "Pet Supplies",
    category: ["Shopping", "Personal Care"],
  },
  {
    date: "2024-07-29",
    amount: -70,
    logo_url: "",
    merchant_name: "Target",
    name: "Household Supplies",
    category: ["Shopping", "Utilities"],
  },
  {
    date: "2024-07-05",
    amount: -45,
    logo_url: "",
    merchant_name: "Vitamin Shoppe",
    name: "Supplements",
    category: ["Health and Fitness"],
  },
  {
    date: "2024-07-15",
    amount: -60,
    logo_url: "",
    merchant_name: "24 Hour Fitness",
    name: "Monthly Gym Membership",
    category: ["Health and Fitness"],
  },
  {
    date: "2024-07-20",
    amount: -25,
    logo_url: "",
    merchant_name: "Whole Foods",
    name: "Organic Health Snacks",
    category: ["Health and Fitness"],
  },
  {
    date: "2024-07-30",
    amount: -29,
    logo_url: "",
    merchant_name: "GNC",
    name: "Health Supplements",
    category: ["Health and Fitness"],
  },

  // Agosto
  {
    date: "2024-08-12",
    amount: -15.99,
    logo_url: "",
    merchant_name: "Spotify",
    name: "Spotify Premium",
    category: ["Subscription", "Entertainment"],
  },
  {
    date: "2024-08-15",
    amount: -9.99,
    logo_url: "",
    merchant_name: "Apple Music",
    name: "Apple Music Subscription",
    category: ["Subscription", "Entertainment"],
  },
  {
    date: "2024-08-28",
    amount: -12.99,
    logo_url: "",
    merchant_name: "Disney+",
    name: "Disney+ Subscription",
    category: ["Subscription", "Entertainment"],
  },
  {
    date: "2024-08-10",
    amount: -32,
    logo_url: "",
    merchant_name: "Chipotle",
    name: "Chipotle Mexican Grill",
    category: ["Food and Drink", "Restaurants"],
  },
  {
    date: "2024-08-16",
    amount: -75,
    logo_url: "",
    merchant_name: "Whole Foods Market",
    name: "Groceries",
    category: ["Food and Drink", "Groceries"],
  },
  {
    date: "2024-08-22",
    amount: -12.5,
    logo_url: "",
    merchant_name: "Safeway",
    name: "Safeway Groceries",
    category: ["Food and Drink", "Groceries"],
  },
  {
    date: "2024-08-25",
    amount: -18,
    logo_url: "",
    merchant_name: "Dunkin' Donuts",
    name: "Coffee and Snacks",
    category: ["Food and Drink", "Coffee Shop"],
  },
  {
    date: "2024-08-28",
    amount: -60,
    logo_url: "",
    merchant_name: "Planet Fitness",
    name: "Gym Membership",
    category: ["Health and Fitness", "Subscription"],
  },
  {
    date: "2024-08-10",
    amount: -150,
    logo_url: "",
    merchant_name: "Home Depot",
    name: "Paint Supplies",
    category: ["Shopping", "Home Improvement"],
  },
  {
    date: "2024-08-22",
    amount: -85,
    logo_url: "",
    merchant_name: "Lowe's",
    name: "Garden Tools",
    category: ["Shopping", "Home Improvement"],
  },
  {
    date: "2024-08-25",
    amount: -200,
    logo_url: "",
    merchant_name: "Wayfair",
    name: "Living Room Furniture",
    category: ["Shopping", "Home Improvement"],
  },
  {
    date: "2024-08-29",
    amount: -100,
    logo_url: "",
    merchant_name: "IKEA",
    name: "Furniture Purchase",
    category: ["Shopping", "Home Improvement"],
  },

  // Septiembre
  {
    date: "2024-09-03",
    amount: -110,
    logo_url: "",
    merchant_name: "Home Depot",
    name: "Home Supplies",
    category: ["Shopping", "Utilities"],
  },
  {
    date: "2024-09-02",
    amount: -25,
    logo_url: "",
    merchant_name: "Pizza Hut",
    name: "Pizza Hut Order",
    category: ["Food and Drink", "Restaurants"],
  },
  {
    date: "2024-09-04",
    amount: -42,
    logo_url: "",
    merchant_name: "McDonald's",
    name: "McDonald's Meal",
    category: ["Food and Drink", "Restaurants"],
  },
  {
    date: "2024-09-10",
    amount: -18,
    logo_url: "",
    merchant_name: "KFC",
    name: "KFC Meal",
    category: ["Food and Drink", "Restaurants"],
  },
  {
    date: "2024-09-18",
    amount: -30,
    logo_url: "",
    merchant_name: "Subway",
    name: "Subway Sandwiches",
    category: ["Food and Drink", "Restaurants"],
  },
  {
    date: "2024-09-10",
    amount: -150,
    logo_url: "",
    merchant_name: "Airbnb",
    name: "Airbnb Stay",
    category: ["Travel"],
  },
  {
    date: "2024-09-05",
    amount: -12.99,
    logo_url: "",
    merchant_name: "HBO Max",
    name: "HBO Max Subscription",
    category: ["Subscription", "Entertainment"],
  },
  {
    date: "2024-09-17",
    amount: -15.99,
    logo_url: "",
    merchant_name: "Spotify",
    name: "Spotify Premium",
    category: ["Subscription", "Entertainment"],
  },
  {
    date: "2024-09-22",
    amount: -15,
    logo_url: "",
    merchant_name: "Regal Cinemas",
    name: "Movie Ticket",
    category: ["Entertainment"],
  },
  {
    date: "2024-09-29",
    amount: -27,
    logo_url: "",
    merchant_name: "AMC Theatres",
    name: "Movie Ticket",
    category: ["Entertainment"],
  },
  {
    date: "2024-09-05",
    amount: -25,
    logo_url: "",
    merchant_name: "Barnes & Noble",
    name: "Books",
    category: ["Shopping", "Education"],
  },
  {
    date: "2024-09-12",
    amount: -60,
    logo_url: "",
    merchant_name: "Office Depot",
    name: "Office Supplies",
    category: ["Shopping", "Education"],
  },
  {
    date: "2024-09-18",
    amount: -85,
    logo_url: "",
    merchant_name: "Bed Bath & Beyond",
    name: "Home Decor",
    category: ["Shopping", "Home Improvement"],
  },
  {
    date: "2024-09-30",
    amount: -45,
    logo_url: "",
    merchant_name: "Home Goods",
    name: "Home Decoration",
    category: ["Shopping", "Home Improvement"],
  },

  // Octubre
  {
    date: "2024-10-02",
    amount: -65,
    logo_url: "",
    merchant_name: "Sephora",
    name: "Cosmetics Purchase",
    category: ["Personal Care", "Shopping"],
  },
  {
    date: "2024-10-05",
    amount: -80,
    logo_url: "",
    merchant_name: "AT&T",
    name: "Phone Bill",
    category: ["Utilities", "Service"],
  },
  {
    date: "2024-10-09",
    amount: -100,
    logo_url: "",
    merchant_name: "Sprint",
    name: "Mobile Bill",
    category: ["Utilities", "Service"],
  },
  {
    date: "2024-10-12",
    amount: -120,
    logo_url: "",
    merchant_name: "Comcast",
    name: "Cable Bill",
    category: ["Utilities", "Service"],
  },
  {
    date: "2024-10-15",
    amount: -20,
    logo_url: "",
    merchant_name: "Starbucks",
    name: "Coffee",
    category: ["Food and Drink", "Coffee Shop"],
  },
  
  {
    date: "2024-10-18",
    amount: -45,
    logo_url: "",
    merchant_name: "Amazon",
    name: "Shopping",
    category: ["Shopping"],
  },
  {
    date: "2024-10-22",
    amount: -15,
    logo_url: "",
    merchant_name: "Dunkin' Donuts",
    name: "Breakfast",
    category: ["Food and Drink", "Coffee Shop"],
  },
  {
    date: "2024-10-25",
    amount: -30,
    logo_url: "",
    merchant_name: "McDonald's",
    name: "Lunch",
    category: ["Food and Drink", "Restaurants"],
  },
  {
    date: "2024-10-20",
    amount: -65,
    logo_url: "",
    merchant_name: "Verizon",
    name: "Internet Bill",
    category: ["Utilities", "Service"],
  },
  {
    date: "2024-10-02",
    amount: -9.99,
    logo_url: "",
    merchant_name: "Spotify",
    name: "Spotify Subscription",
    category: ["Subscription", "Entertainment"],
  },
  {
    date: "2024-10-03",
    amount: -120,
    logo_url: "",
    merchant_name: "Apple Store",
    name: "Gadget Purchase",
    category: ["Shopping", "Electronics"],
  },
  {
    date: "2024-10-27",
    amount: -12.99,
    logo_url: "",
    merchant_name: "Netflix",
    name: "Netflix Subscription",
    category: ["Subscription", "Entertainment"],
  },
  {
    date: "2024-10-29",
    amount: -75,
    logo_url: "",
    merchant_name: "Best Buy",
    name: "Electronics Purchase",
    category: ["Shopping", "Electronics"],
  },
  {
    date: "2024-10-30",
    amount: -19.99,
    logo_url: "",
    merchant_name: "Disney+",
    name: "Disney+ Subscription",
    category: ["Subscription", "Entertainment"],
  },
];

export default plaidTransactions;
